export const API_KEY = "API_KEY";

export const FETCH_HOME_LIVESTREAM_REQUEST = "FETCH_HOME_LIVESTREAM_REQUEST";
export const FETCH_HOME_LIVESTREAM_SUCCESS = "FETCH_HOME_LIVESTREAM_SUCCESS";
export const FETCH_HOME_LIVESTREAM_FAILURE = "FETCH_HOME_LIVESTREAM_FAILURE";

export const FETCH_HOME_FEATURED_COURSES_REQUEST = 'FETCH_HOME_FEATURED_COURSES_REQUEST';
export const FETCH_HOME_FEATURED_COURSES_SUCCESS = 'FETCH_HOME_FEATURED_COURSES_SUCCESS';
export const FETCH_HOME_FEATURED_COURSES_FAILURE = 'FETCH_HOME_FEATURED_COURSES_FAILURE';
// All Live Stream
export const FETCH_STREAMS_REQUEST = "FETCH_STREAMS_REQUEST";
export const FETCH_STREAMS_SUCCESS = "FETCH_STREAMS_SUCCESS";
export const FETCH_STREAMS_FAILURE = "FETCH_STREAMS_FAILURE";

//All Instructor
export const FETCH_INSTRUCTORS_REQUEST = "FETCH_INSTRUCTORS_REQUEST";
export const FETCH_INSTRUCTORS_SUCCESS = "FETCH_INSTRUCTORS_SUCCESS";
export const FETCH_INSTRUCTORS_FAILURE = "FETCH_INSTRUCTORS_FAILURE";
export const SEARCH_INSTRUCTORS_REQUEST = "SEARCH_INSTRUCTORS_REQUEST";
export const FETCH_INSTRUCTOR_BY_ID_REQUEST = "FETCH_INSTRUCTOR_BY_ID_REQUEST";

//Search Result
export const FETCH_SEARCH_RESULT_REQUEST = "FETCH_SEARCH_RESULT_REQUEST";
export const FETCH_SEARCH_RESULT_SUCCESS = "FETCH_SEARCH_RESULT_SUCCESS";
export const FETCH_SEARCH_RESULT_FAILURE = "FETCH_SEARCH_RESULT_FAILURE";
